add tests for views: get (all assets) and post (logic of subscription…
esgaelramos/YourMoneyTrackerMail pull request #62
Opened 2023-12-12 06:40 UTC by esgaelramos

… and send mail), create unit tests for models of moneytracker app

2023-12-12 19:23 UTC, CamilaPua requested changes

2023-12-12 19:23 UTC, CamilaPua commented on tests/test_moneytracker/test_models.py
> +        self.assertEqual(str(portfolio_example), f'Portfolio of Mocked CustomUser')
the format

2023-12-12 19:23 UTC, CamilaPua commented on tests/test_moneytracker/test_models.py
> +        self.assertEqual(str(portfolioasset_example), f'Mocked Asset portfolio of Mocked Portfolio')
the format

2023-12-12 19:23 UTC, CamilaPua commented on tests/test_moneytracker/test_models.py
> +        self.assertEqual(str(performance_example), f'Performance of Mocked CustomUser')
and the format c: thankkks

2023-12-12 19:33 UTC, esgaelramos commented on tests/test_moneytracker/test_models.py
> +        self.assertEqual(str(performance_example), f'Performance of Mocked CustomUser')
im sorry, forget delete the 'f':(

2023-12-12 21:10 UTC, CamilaPua approved these changes

2023-12-12 21:15 UTC, merged

2023-12-17 16:26 UTC, CamilaPua commented
0

0
0
0
0

0
0
000  00.  00
 0. yo

000
0000


Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
From: Gael Ramos ***@***.***>
Sent: Tuesday, December 12, 2023 4:16:04 PM
To: esgaelramos/YourMoneyTrackerMail ***@***.***>
Cc: ARCINIEGAS PUA MARIA ***@***.***>; Review requested ***@***.***>
Subject: Re: [esgaelramos/YourMoneyTrackerMail] add tests for views: get (all assets) and post (logic of subscription… (PR #62)


Merged #62<https://github.com/esgaelramos/YourMoneyTrackerMail/pull/62> into main.

—
Reply to this email directly, view it on GitHub<https://github.com/esgaelramos/YourMoneyTrackerMail/pull/62#event-11228719560>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A5BN2KNVRQVZVLYLXZUEPH3YJDCRJAVCNFSM6AAAAABAQ57XIKVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJRGIZDQNZRHE2TMMA>.
You are receiving this because your review was requested.Message ID: ***@***.***>