Models Creation
esgaelramos/YourMoneyTrackerMail pull request #7
Opened 2023-11-29 23:31 UTC by LorenzoFerreyra

creacion de modelos para database

2023-11-29 23:53 UTC, esgaelramos requested changes

2023-11-29 23:53 UTC, esgaelramos commented on moneytracker/models.py
> +    performance = models.DecimalField(max_digits=5, decimal_places=2)
por fa elimina este campo, se puede caluclar

2023-11-29 23:54 UTC, LorenzoFerreyra commented on moneytracker/models.py
> +    performance = models.DecimalField(max_digits=5, decimal_places=2)
perfecto

2023-11-30 00:03 UTC, LorenzoFerreyra reviewed
creo que ahi lo pude eliminar

2023-11-30 22:48 UTC, closed without merging